### ISSUE TITLE
Unable to obtain certificate

### ISSUE THREAD

**Issue by rkosegi** [jahudka/certbot-dns-active24#6]
Just tried to obtain certificate and got following error:

```
Encountered exception during recovery: 
Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/certbot/_internal/auth_handler.py", line 70, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/root/.local/lib/python3.6/site-packages/certbot/plugins/dns_common.py", line 57, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/root/.local/lib/python3.6/site-packages/certbot_dns_active24/dns_active24.py", line 60, in _perform
    _wait_for_propagation(validation_name)
  File "/root/.local/lib/python3.6/site-packages/certbot_dns_active24/dns_active24.py", line 70, in _wait_for_propagation
    nss = _get_nameservers(validation_name)
  File "/root/.local/lib/python3.6/site-packages/certbot_dns_active24/dns_active24.py", line 96, in _get_nameservers
    rrset = answer if len(answer) > 0 else answer.response.authority[0]
IndexError: list index out of range


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/certbot/_internal/error_handler.py", line 125, in _call_registered
    self.funcs[-1]()
  File "/root/.local/lib/python3.6/site-packages/certbot/_internal/auth_handler.py", line 243, in _cleanup_challenges
    self.auth.cleanup(achalls)
  File "/root/.local/lib/python3.6/site-packages/certbot/plugins/dns_common.py", line 76, in cleanup
    self._cleanup(domain, validation_domain_name, validation)
  File "/root/.local/lib/python3.6/site-packages/certbot_dns_active24/dns_active24.py", line 63, in _cleanup
    self._get_active24_client().del_txt_record(validation_name, validation)
  File "/root/.local/lib/python3.6/site-packages/certbot_dns_active24/dns_active24.py", line 162, in del_txt_record
    hash_id = self._find_hash_id(domain, record)
  File "/root/.local/lib/python3.6/site-packages/certbot_dns_active24/dns_active24.py", line 182, in _find_hash_id
    raise RuntimeError('Cannot find TXT record "{0}" for domain "{1}"'.format(record_name, domain_name))
RuntimeError: Cannot find TXT record "_acme-challenge" for domain "domain.tld"
An unexpected error occurred:

```

Plugin version
```
pip3 show certbot-dns-active24
Name: certbot-dns-active24
Version: 1.1.6
Summary: Active24 DNS authenticator plugin for Certbot
Home-page: https://github.com/jahudka/certbot-dns-active24
Author: Dan Kadera
Author-email: me@subsonic.cz
License: MIT
Location: /root/.local/lib/python3.6/site-packages
Requires: acme, certbot, dnspython, requests, mock, setuptools, zope.interface
```

Debug log (redacted)

```
2020-05-01 17:56:39,445:DEBUG:certbot._internal.main:certbot version: 1.3.0
2020-05-01 17:56:39,447:DEBUG:certbot._internal.main:Arguments: ['--non-interactive', '--test-cert', '--agree-tos', '--email', 'admin@domain.tld', '-a', 'certbot-dns-active24:dns', '-d', 'domain.tld', '-d', '*.domain.tld']
2020-05-01 17:56:39,448:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#certbot-dns-active24:dns,PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2020-05-01 17:56:39,462:DEBUG:certbot._internal.log:Root logging level set at 20
2020-05-01 17:56:39,463:INFO:certbot._internal.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2020-05-01 17:56:39,464:DEBUG:certbot._internal.plugins.selection:Requested authenticator certbot-dns-active24:dns and installer None
2020-05-01 17:56:39,469:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * certbot-dns-active24:dns
Description: Obtain certificates using a DNS TXT record (if you are using Active24 for DNS).
Interfaces: IAuthenticator, IPlugin
Entry point: dns = certbot_dns_active24.dns_active24:Authenticator
Initialized: <certbot_dns_active24.dns_active24.Authenticator object at 0x7fd22b16a048>
Prep: True
2020-05-01 17:56:39,470:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot_dns_active24.dns_active24.Authenticator object at 0x7fd22b16a048> and installer None
2020-05-01 17:56:39,470:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator certbot-dns-active24:dns, Installer None
2020-05-01 17:56:39,474:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-staging-v02.api.letsencrypt.org/acme/acct/13441234', new_authzr_uri=None, terms_of_service=None), 661b0e5795af23987d1f3d73d62e9947, Meta(creation_dt=datetime.datetime(2020, 5, 1, 17, 51, 23, tzinfo=<UTC>), creation_host='e661ff35c79f'))>
2020-05-01 17:56:39,476:DEBUG:acme.client:Sending GET request to https://acme-staging-v02.api.letsencrypt.org/directory.
2020-05-01 17:56:39,479:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-staging-v02.api.letsencrypt.org:443
2020-05-01 17:56:40,292:DEBUG:urllib3.connectionpool:https://acme-staging-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 724
2020-05-01 17:56:40,295:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Fri, 01 May 2020 17:56:40 GMT
Content-Type: application/json
Content-Length: 724
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "j_A0uxwqSrw": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-staging-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org/docs/staging-environment/"
  },
  "newAccount": "https://acme-staging-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-staging-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-staging-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-staging-v02.api.letsencrypt.org/acme/revoke-cert"
}
2020-05-01 17:56:40,297:INFO:certbot._internal.main:Obtaining a new certificate
2020-05-01 17:56:40,488:DEBUG:certbot.crypto_util:Generating key (2048 bits): /etc/letsencrypt/keys/0001_key-certbot.pem
2020-05-01 17:56:40,489:DEBUG:certbot.crypto_util:Creating CSR: /etc/letsencrypt/csr/0001_csr-certbot.pem
2020-05-01 17:56:40,490:DEBUG:acme.client:Requesting fresh nonce
2020-05-01 17:56:40,490:DEBUG:acme.client:Sending HEAD request to https://acme-staging-v02.api.letsencrypt.org/acme/new-nonce.
2020-05-01 17:56:40,702:DEBUG:urllib3.connectionpool:https://acme-staging-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2020-05-01 17:56:40,703:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Fri, 01 May 2020 17:56:40 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-staging-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0002MBoj-BWlg1jwLfnVwBg9yYbiFhzyDFn8bHibLKTv1pU
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2020-05-01 17:56:40,704:DEBUG:acme.client:Storing nonce: 0002MBoj-BWlg1jwLfnVwBg9yYbiFhzyDFn8bHibLKTv1pU
2020-05-01 17:56:40,705:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "domain.tld"\n    },\n    {\n      "type": "dns",\n      "value": "*.domain.tld"\n    }\n  ]\n}'
2020-05-01 17:56:40,715:DEBUG:acme.client:Sending POST request to https://acme-staging-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "<REDACTED>",
  "signature": "<REDACTED>",
  "payload": "<REDACTED>"
}
2020-05-01 17:56:41,015:DEBUG:urllib3.connectionpool:https://acme-staging-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 483
2020-05-01 17:56:41,017:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Fri, 01 May 2020 17:56:40 GMT
Content-Type: application/json
Content-Length: 483
Connection: keep-alive
Boulder-Requester: 13441234
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-staging-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-staging-v02.api.letsencrypt.org/acme/order/13441234/88848151
Replay-Nonce: 0002V59ZLfkkOOSwt09ogmUD4GTHdZYjyh5jHpobAhmfZ_o
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "pending",
  "expires": "2020-05-08T17:51:55Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "*.domain.tld"
    },
    {
      "type": "dns",
      "value": "domain.tld"
    }
  ],
  "authorizations": [
    "https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/53066699",
    "https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/53066700"
  ],
  "finalize": "https://acme-staging-v02.api.letsencrypt.org/acme/finalize/13441234/88848151"
}
2020-05-01 17:56:41,018:DEBUG:acme.client:Storing nonce: <REDACTED>
2020-05-01 17:56:41,019:DEBUG:acme.client:JWS payload:
b''
2020-05-01 17:56:41,024:DEBUG:acme.client:Sending POST request to https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/53066699:
{
  "protected": "<REDACTED>",
  "signature": "<REDACTED>",
  "payload": ""
}
2020-05-01 17:56:41,316:DEBUG:urllib3.connectionpool:https://acme-staging-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/53066699 HTTP/1.1" 200 389
2020-05-01 17:56:41,318:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Fri, 01 May 2020 17:56:41 GMT
Content-Type: application/json
Content-Length: 389
Connection: keep-alive
Boulder-Requester: 13441234
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-staging-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0002Pljla5TwmojltnjMn7Sp8gZRqCw1D_apeXxxdnAtC0M
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "domain.tld"
  },
  "status": "pending",
  "expires": "2020-05-08T17:51:55Z",
  "challenges": [
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/53066699/32-rsA",
      "token": "<REDACTED>"
    }
  ],
  "wildcard": true
}
2020-05-01 17:56:41,319:DEBUG:acme.client:Storing nonce: <REDACTED>
2020-05-01 17:56:41,320:DEBUG:acme.client:JWS payload:
b''
2020-05-01 17:56:41,325:DEBUG:acme.client:Sending POST request to https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/53066700:
{
  "protected": "<REDACTED>",
  "signature": "<REDACTED>",
  "payload": ""
}
2020-05-01 17:56:41,623:DEBUG:urllib3.connectionpool:https://acme-staging-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/53066700 HTTP/1.1" 200 807
2020-05-01 17:56:41,625:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Fri, 01 May 2020 17:56:41 GMT
Content-Type: application/json
Content-Length: 807
Connection: keep-alive
Boulder-Requester: 13441234
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-staging-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0001CpYUUdjAX5cX2mk6233HyEvnzyiaOUKrXBtysfGrjRI
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "domain.tld"
  },
  "status": "pending",
  "expires": "2020-05-08T17:51:55Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "url": "https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/53066700/tI99_Q",
      "token": "<REDACTED>"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/53066700/avKgDw",
      "token": "<REDACTED>"
    },
    {
      "type": "tls-alpn-01",
      "status": "pending",
      "url": "https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/53066700/7Bm44A",
      "token": "<REDACTED>"
    }
  ]
}
2020-05-01 17:56:41,626:DEBUG:acme.client:Storing nonce: 0001CpYUUdjAX5cX2mk6233HyEvnzyiaOUKrXBtysfGrjRI
2020-05-01 17:56:41,628:INFO:certbot._internal.auth_handler:Performing the following challenges:
2020-05-01 17:56:41,629:INFO:certbot._internal.auth_handler:dns-01 challenge for domain.tld
2020-05-01 17:56:41,630:INFO:certbot._internal.auth_handler:dns-01 challenge for domain.tld
2020-05-01 17:56:41,631:WARNING:certbot.plugins.dns_common:Unsafe permissions on credentials configuration file: /etc/letsencrypt/active24.ini
2020-05-01 17:56:41,639:DEBUG:certbot_dns_active24.dns_active24:Attempting to add record: _acme-challenge
2020-05-01 17:56:41,644:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.active24.com:443
2020-05-01 17:56:42,851:DEBUG:urllib3.connectionpool:https://api.active24.com:443 "POST /dns/domain.tld/txt/v1 HTTP/1.1" 204 0
2020-05-01 17:56:42,853:DEBUG:certbot_dns_active24.dns_active24:Successfully added TXT record
2020-05-01 17:56:42,901:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/certbot/_internal/auth_handler.py", line 70, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/root/.local/lib/python3.6/site-packages/certbot/plugins/dns_common.py", line 57, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/root/.local/lib/python3.6/site-packages/certbot_dns_active24/dns_active24.py", line 60, in _perform
    _wait_for_propagation(validation_name)
  File "/root/.local/lib/python3.6/site-packages/certbot_dns_active24/dns_active24.py", line 70, in _wait_for_propagation
    nss = _get_nameservers(validation_name)
  File "/root/.local/lib/python3.6/site-packages/certbot_dns_active24/dns_active24.py", line 97, in _get_nameservers
    rrset = answer if len(answer) > 0 else answer.response.authority[0]
IndexError: list index out of range

2020-05-01 17:56:42,901:DEBUG:certbot._internal.error_handler:Calling registered functions
2020-05-01 17:56:42,901:INFO:certbot._internal.auth_handler:Cleaning up challenges
2020-05-01 17:56:42,903:DEBUG:certbot_dns_active24.dns_active24:Attempting to delete record: _acme-challenge
2020-05-01 17:56:42,906:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.active24.com:443
2020-05-01 17:56:43,468:DEBUG:urllib3.connectionpool:https://api.active24.com:443 "GET /dns/domain.tld/records/v1 HTTP/1.1" 200 1864
2020-05-01 17:56:43,479:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.active24.com:443
2020-05-01 17:56:44,735:DEBUG:urllib3.connectionpool:https://api.active24.com:443 "DELETE /dns/domain.tld/<REDACTED>/v1 HTTP/1.1" 204 0
2020-05-01 17:56:44,741:DEBUG:certbot_dns_active24.dns_active24:Successfully deleted TXT record.
2020-05-01 17:56:44,746:DEBUG:certbot_dns_active24.dns_active24:Attempting to delete record: _acme-challenge
2020-05-01 17:56:44,751:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.active24.com:443
2020-05-01 17:56:45,676:DEBUG:urllib3.connectionpool:https://api.active24.com:443 "GET /dns/domain.tld/records/v1 HTTP/1.1" 200 1717
2020-05-01 17:56:45,679:ERROR:certbot._internal.error_handler:Encountered exception during recovery: 
Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/certbot/_internal/auth_handler.py", line 70, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/root/.local/lib/python3.6/site-packages/certbot/plugins/dns_common.py", line 57, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/root/.local/lib/python3.6/site-packages/certbot_dns_active24/dns_active24.py", line 60, in _perform
    _wait_for_propagation(validation_name)
  File "/root/.local/lib/python3.6/site-packages/certbot_dns_active24/dns_active24.py", line 70, in _wait_for_propagation
    nss = _get_nameservers(validation_name)
  File "/root/.local/lib/python3.6/site-packages/certbot_dns_active24/dns_active24.py", line 97, in _get_nameservers
    rrset = answer if len(answer) > 0 else answer.response.authority[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/certbot/_internal/error_handler.py", line 125, in _call_registered
    self.funcs[-1]()
  File "/root/.local/lib/python3.6/site-packages/certbot/_internal/auth_handler.py", line 243, in _cleanup_challenges
    self.auth.cleanup(achalls)
  File "/root/.local/lib/python3.6/site-packages/certbot/plugins/dns_common.py", line 76, in cleanup
    self._cleanup(domain, validation_domain_name, validation)
  File "/root/.local/lib/python3.6/site-packages/certbot_dns_active24/dns_active24.py", line 63, in _cleanup
    self._get_active24_client().del_txt_record(validation_name, validation)
  File "/root/.local/lib/python3.6/site-packages/certbot_dns_active24/dns_active24.py", line 163, in del_txt_record
    hash_id = self._find_hash_id(domain, record)
  File "/root/.local/lib/python3.6/site-packages/certbot_dns_active24/dns_active24.py", line 183, in _find_hash_id
    raise RuntimeError('Cannot find TXT record "{0}" for domain "{1}"'.format(record_name, domain_name))
RuntimeError: Cannot find TXT record "_acme-challenge" for domain "domain.tld"
2020-05-01 17:56:45,680:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/root/.local/bin/certbot", line 11, in <module>
    sys.exit(main())
  File "/root/.local/lib/python3.6/site-packages/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/root/.local/lib/python3.6/site-packages/certbot/_internal/main.py", line 1347, in main
    return config.func(config, plugins)
  File "/root/.local/lib/python3.6/site-packages/certbot/_internal/main.py", line 1233, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/root/.local/lib/python3.6/site-packages/certbot/_internal/main.py", line 121, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/root/.local/lib/python3.6/site-packages/certbot/_internal/client.py", line 410, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/root/.local/lib/python3.6/site-packages/certbot/_internal/client.py", line 344, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/root/.local/lib/python3.6/site-packages/certbot/_internal/client.py", line 391, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/root/.local/lib/python3.6/site-packages/certbot/_internal/auth_handler.py", line 70, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/root/.local/lib/python3.6/site-packages/certbot/plugins/dns_common.py", line 57, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/root/.local/lib/python3.6/site-packages/certbot_dns_active24/dns_active24.py", line 60, in _perform
    _wait_for_propagation(validation_name)
  File "/root/.local/lib/python3.6/site-packages/certbot_dns_active24/dns_active24.py", line 70, in _wait_for_propagation
    nss = _get_nameservers(validation_name)
  File "/root/.local/lib/python3.6/site-packages/certbot_dns_active24/dns_active24.py", line 97, in _get_nameservers
    rrset = answer if len(answer) > 0 else answer.response.authority[0]
IndexError: list index out of range

```

**Comment by jahudka** [comment]
Hi, thanks for reporting, but it might be hard to reproduce / fix this issue..

 - The plugin correctly adds the appropriate TXT record
 - But then it tries to obtain a list of authoritative nameservers for the domain so that it can query them until they all respond with the correct TXT record
 - That DNS query results in an empty answer - which means there is no explicit NS record for the full DNS name, so the plugin tries to figure out where else to look by examining the authority section of the response - this should typically include the DNS name of the zone in which the TXT record is located, which the plugin would then examine to figure out the authoritative nameservers; but for some reason the DNS query for the nameservers for your specific domain not only doesn't return any answers, but it appears it doesn't return an authority section either, and the plugin, expecting to find one, just fails

Try manually running `dig` from the server where you are running the plugin. If the domain for which you are trying to obtain a certificate is called `domain.tld`, you'd run this:
```
dig _acme-challenge.domain.tld NS
```
If the domain was `my-project.subdomain.domain.tld`, you'd run:
```
dig _acme-challenge.my-project.subdomain.domain.tld NS
```
The output of that command could look something like this:
```
; <<>> DiG 9.10.6 <<>> ns _acme-challenge.domain.tld
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: NNNN
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;_acme-challenge.domain.tld. IN NS

;; AUTHORITY SECTION:
domain.tld.		NNNN	IN	SOA	alfa.ns.active24.cz. hostmaster.active24.cz. nnn nn nn nn

;; Query time: NN msec
;; SERVER: N.N.N.N#53
;; WHEN: Fri May 01 21:51:20 CEST 2020
;; MSG SIZE  rcvd: NNN
```

You can see there is no `;; ANSWER SECTION`, but there should be an `AUTHORITY` section. Can you confirm that?

**Comment by rkosegi** [comment]
Hi, here is output (my domain redacted to domain.tld)

```
dig _acme-challenge.domain.tld NS

; <<>> DiG 9.11.14-RedHat-9.11.14-2.fc31 <<>> _acme-challenge.domain.tld NS
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 55527
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 2, ADDITIONAL: 2

;; QUESTION SECTION:
;_acme-challenge.domain.tld.	IN	NS

;; AUTHORITY SECTION:
domain.tld.		3245	IN	NS	beta.ns.active24.cz.
domain.tld.		3245	IN	NS	alfa.ns.active24.cz.

;; ADDITIONAL SECTION:
beta.ns.active24.cz.	3055	IN	A	81.0.238.27
alfa.ns.active24.cz.	3142	IN	A	81.95.96.2

;; Query time: 56 msec
;; SERVER: 192.168.1.3#53(192.168.1.3)
;; WHEN: Fri May 01 22:16:44 CEST 2020
;; MSG SIZE  rcvd: 129
```

**Comment by jahudka** [comment]
Hi, that looks okay.. Well, the only other test I can think of is to try running the Python code that's causing the error directly to see what's happening there. Copy the following code:
```python
from dns.resolver import get_default_resolver

resolver = get_default_resolver()
answer = resolver.query('_acme-challenge.domain.tld', 'NS', raise_on_no_answer=False)
print('answer: %d records' % len(answer))
print('authority: %d records' % len(answer.response.authority))
print(answer.response.to_text())
```
Save it to a file named e.g. `test.py` on your server; change the domain on line 4 to yours obviously. Now run it with `python3 test.py`. The output should be something like this:
```
answer: 0 records
authority: 1 records
id NNNNN
opcode QUERY
rcode NOERROR
flags QR RD RA
;QUESTION
_acme-challenge.domain.tld. IN NS
;ANSWER
;AUTHORITY
domain.tld. 3600 IN SOA alfa.ns.active24.cz. hostmaster.active24.cz. nnnn nnnn nnn nnn
;ADDITIONAL
```

**Comment by rkosegi** [comment]
Hi, here is output

```
python3.6 1.py
answer: 0 records
authority: 1 records
id 14170
opcode QUERY
rcode NOERROR
flags QR RD RA
;QUESTION
_acme-challenge.domain.tld. IN NS
;ANSWER
;AUTHORITY
domain.tld. 600 IN SOA alfa.ns.active24.cz. hostmaster.active24.cz. 2020050140 10800 1800 1209600 3600
;ADDITIONAL

```

**Comment by jahudka** [comment]
Hi, so sorry for the delay.. Did you manage to get it to work in the end?

**Comment by rkosegi** [comment]
> Hi, so sorry for the delay.. Did you manage to get it to work in the end?

I did, by running cerbot in debugger and stepping over plugin code. I don't remeber exact details, but I was able to pass validation. I will retry when cert is about to expire and update here

**Comment by jahudka** [comment]
ok, just try updating the plugin beforehand, I've released a couple of fixes recently, might affect you..

**Comment by rkosegi** [comment]
Retried, no luck.

```
docker run -v $(readlink -f .):/letsencrypt -ti python:latest bash
```

```
pip3 install certbot-dns-active24
Collecting certbot-dns-active24
  Downloading certbot-dns-active24-1.1.14.tar.gz (7.0 kB)
Collecting acme>=0.21.1
  Downloading acme-1.5.0-py2.py3-none-any.whl (41 kB)
     |████████████████████████████████| 41 kB 595 kB/s 
Collecting certbot>=0.21.1
  Downloading certbot-1.5.0-py2.py3-none-any.whl (232 kB)
     |████████████████████████████████| 232 kB 2.3 MB/s 
Collecting dnspython>=1.16.0
  Downloading dnspython-1.16.0-py2.py3-none-any.whl (188 kB)
     |████████████████████████████████| 188 kB 1.6 MB/s 
Collecting requests>=2.9.1
  Downloading requests-2.24.0-py2.py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 244 kB/s 
Collecting mock
  Downloading mock-4.0.2-py3-none-any.whl (28 kB)
Requirement already satisfied: setuptools in /usr/local/lib/python3.8/site-packages (from certbot-dns-active24) (47.1.1)
Collecting zope.interface
  Downloading zope.interface-5.1.0-cp38-cp38-manylinux2010_x86_64.whl (243 kB)
     |████████████████████████████████| 243 kB 1.8 MB/s 
Collecting cryptography>=1.2.3
  Downloading cryptography-2.9.2-cp35-abi3-manylinux2010_x86_64.whl (2.7 MB)
     |████████████████████████████████| 2.7 MB 739 kB/s 
Collecting pyrfc3339
  Downloading pyRFC3339-1.1-py2.py3-none-any.whl (5.7 kB)
Collecting josepy>=1.1.0
  Downloading josepy-1.3.0-py2.py3-none-any.whl (57 kB)
     |████████████████████████████████| 57 kB 1.1 MB/s 
Collecting pytz
  Downloading pytz-2020.1-py2.py3-none-any.whl (510 kB)
     |████████████████████████████████| 510 kB 1.6 MB/s 
Collecting PyOpenSSL>=0.13.1
  Downloading pyOpenSSL-19.1.0-py2.py3-none-any.whl (53 kB)
     |████████████████████████████████| 53 kB 597 kB/s 
Collecting requests-toolbelt>=0.3.0
  Downloading requests_toolbelt-0.9.1-py2.py3-none-any.whl (54 kB)
     |████████████████████████████████| 54 kB 1.2 MB/s 
Collecting six>=1.9.0
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting ConfigArgParse>=0.9.3
  Downloading ConfigArgParse-1.2.3.tar.gz (42 kB)
     |████████████████████████████████| 42 kB 723 kB/s 
Collecting zope.component
  Downloading zope.component-4.6.1-py2.py3-none-any.whl (66 kB)
     |████████████████████████████████| 66 kB 2.1 MB/s 
Collecting parsedatetime>=1.3
  Downloading parsedatetime-2.6-py3-none-any.whl (42 kB)
     |████████████████████████████████| 42 kB 797 kB/s 
Collecting distro>=1.0.1
  Downloading distro-1.5.0-py2.py3-none-any.whl (18 kB)
Collecting configobj
  Downloading configobj-5.0.6.tar.gz (33 kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Downloading urllib3-1.25.9-py2.py3-none-any.whl (126 kB)
     |████████████████████████████████| 126 kB 1.8 MB/s 
Collecting idna<3,>=2.5
  Downloading idna-2.9-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 2.9 MB/s 
Collecting chardet<4,>=3.0.2
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
     |████████████████████████████████| 133 kB 1.8 MB/s 
Collecting certifi>=2017.4.17
  Downloading certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
     |████████████████████████████████| 156 kB 2.0 MB/s 
Collecting cffi!=1.11.3,>=1.8
  Downloading cffi-1.14.0-cp38-cp38-manylinux1_x86_64.whl (409 kB)
     |████████████████████████████████| 409 kB 1.9 MB/s 
Collecting zope.event
  Downloading zope.event-4.4-py2.py3-none-any.whl (7.6 kB)
Collecting zope.hookable>=4.2.0
  Downloading zope.hookable-5.0.1-cp38-cp38-manylinux2010_x86_64.whl (26 kB)
Collecting zope.deprecation>=4.3.0
  Downloading zope.deprecation-4.4.0-py2.py3-none-any.whl (10 kB)
Collecting zope.deferredimport>=4.2.1
  Downloading zope.deferredimport-4.3.1-py2.py3-none-any.whl (10 kB)
Collecting pycparser
  Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
     |████████████████████████████████| 112 kB 1.9 MB/s 
Collecting zope.proxy
  Downloading zope.proxy-4.3.5-cp38-cp38-manylinux2010_x86_64.whl (70 kB)
     |████████████████████████████████| 70 kB 2.0 MB/s 
Building wheels for collected packages: certbot-dns-active24, ConfigArgParse, configobj
  Building wheel for certbot-dns-active24 (setup.py) ... done
  Created wheel for certbot-dns-active24: filename=certbot_dns_active24-1.1.14-py2.py3-none-any.whl size=8278 sha256=c21a8bcd180dd2bcc3f85cd4a1efd657903a9a15c486e194e4ace6e3a00edaff
  Stored in directory: /root/.cache/pip/wheels/5f/ea/a7/adb4abae6709bd8a32ede4628e5de3301ef13ad0383e9e8c71
  Building wheel for ConfigArgParse (setup.py) ... done
  Created wheel for ConfigArgParse: filename=ConfigArgParse-1.2.3-py3-none-any.whl size=19326 sha256=7b60289110992f3974e3658516a9068d01431d06523ab8cd50ca9986832d85fd
  Stored in directory: /root/.cache/pip/wheels/b4/12/fe/1e4628f6ec22a9580d9e8fbef23df7a03948a1edde0821d7f5
  Building wheel for configobj (setup.py) ... done
  Created wheel for configobj: filename=configobj-5.0.6-py3-none-any.whl size=34546 sha256=1fd583b0fd960f807af3ee89183fa23fd3f86a25514c20c59aab252fc159b342
  Stored in directory: /root/.cache/pip/wheels/34/2a/24/a490264ae9041fd48f778ff393526572c80bb498ddecb07ea5
Successfully built certbot-dns-active24 ConfigArgParse configobj
Installing collected packages: six, pycparser, cffi, cryptography, pytz, pyrfc3339, PyOpenSSL, josepy, urllib3, idna, chardet, certifi, requests, requests-toolbelt, acme, ConfigArgParse, zope.event, zope.hookable, zope.deprecation, zope.interface, zope.proxy, zope.deferredimport, zope.component, parsedatetime, distro, configobj, certbot, dnspython, mock, certbot-dns-active24
Successfully installed ConfigArgParse-1.2.3 PyOpenSSL-19.1.0 acme-1.5.0 certbot-1.5.0 certbot-dns-active24-1.1.14 certifi-2020.6.20 cffi-1.14.0 chardet-3.0.4 configobj-5.0.6 cryptography-2.9.2 distro-1.5.0 dnspython-1.16.0 idna-2.9 josepy-1.3.0 mock-4.0.2 parsedatetime-2.6 pycparser-2.20 pyrfc3339-1.1 pytz-2020.1 requests-2.24.0 requests-toolbelt-0.9.1 six-1.15.0 urllib3-1.25.9 zope.component-4.6.1 zope.deferredimport-4.3.1 zope.deprecation-4.4.0 zope.event-4.4 zope.hookable-5.0.1 zope.interface-5.1.0 zope.proxy-4.3.5
```

```
root@cf3a297ddc57:/letsencrypt# certbot certonly --non-interactive  --agree-tos --config-dir letsencrypt --logs-dir . --work-dir . -a certbot-active24:dns-credentials=letsencrypt/active24.ini --email admin@acme.com -a certbot-dns-active24:dns -d acme.com -d *.acme.com --certbot-dns-active24:dns-propagation-seconds 360 --certbot-dns-active24:dns-credentials letsencrypt/active24.ini 
Saving debug log to /letsencrypt/letsencrypt.log
Plugins selected: Authenticator certbot-dns-active24:dns, Installer None
Obtaining a new certificate
Performing the following challenges:
dns-01 challenge for acme.com
dns-01 challenge for acme.com
Unsafe permissions on credentials configuration file: letsencrypt/active24.ini
Waiting 360 seconds for DNS changes to propagate
Cleaning up challenges
An unexpected error occurred:
IndexError: list index out of range
Please see the logfiles in /letsencrypt for more details.

root@cf3a297ddc57:/letsencrypt# cat letsencrypt.log
2020-06-25 10:21:54,382:DEBUG:certbot._internal.main:certbot version: 1.5.0
2020-06-25 10:21:54,382:DEBUG:certbot._internal.main:Arguments: ['--non-interactive', '--agree-tos', '--config-dir', 'letsencrypt', '--logs-dir', '.', '--work-dir', '.', '-a', 'certbot-active24:dns-credentials=letsencrypt/active24.ini', '--email', 'admin@acme.com', '-a', 'certbot-dns-active24:dns', '-d', 'acme.com', '-d', '*.acme.com', '--certbot-dns-active24:dns-propagation-seconds', '360', '--certbot-dns-active24:dns-credentials', 'letsencrypt/active24.ini']
2020-06-25 10:21:54,383:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#certbot-dns-active24:dns,PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2020-06-25 10:21:54,399:DEBUG:certbot._internal.log:Root logging level set at 20
2020-06-25 10:21:54,400:INFO:certbot._internal.log:Saving debug log to /letsencrypt/letsencrypt.log
2020-06-25 10:21:54,400:DEBUG:certbot._internal.plugins.selection:Requested authenticator certbot-dns-active24:dns and installer None
2020-06-25 10:21:54,405:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * certbot-dns-active24:dns
Description: Obtain certificates using a DNS TXT record (if you are using Active24 for DNS).
Interfaces: IAuthenticator, IPlugin
Entry point: dns = certbot_dns_active24.dns_active24:Authenticator
Initialized: <certbot_dns_active24.dns_active24.Authenticator object at 0x7f2f58a7fe80>
Prep: True
2020-06-25 10:21:54,405:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot_dns_active24.dns_active24.Authenticator object at 0x7f2f58a7fe80> and installer None
2020-06-25 10:21:54,406:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator certbot-dns-active24:dns, Installer None
2020-06-25 10:21:54,409:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/85006890', new_authzr_uri=None, terms_of_service=None), 39bd431b085889b6aacea7cb04ac36f4, Meta(creation_dt=datetime.datetime(2020, 5, 1, 18, 7, 49, tzinfo=<UTC>), creation_host='e661ff35c79f'))>
2020-06-25 10:21:54,409:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2020-06-25 10:21:54,411:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2020-06-25 10:21:55,180:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 658
2020-06-25 10:21:55,182:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Thu, 25 Jun 2020 10:21:55 GMT
Content-Type: application/json
Content-Length: 658
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "W8W1aOwds3A": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2020-06-25 10:21:55,184:INFO:certbot._internal.main:Obtaining a new certificate
2020-06-25 10:21:55,407:DEBUG:certbot.crypto_util:Generating key (2048 bits): /letsencrypt/letsencrypt/keys/0017_key-certbot.pem
2020-06-25 10:21:55,409:DEBUG:certbot.crypto_util:Creating CSR: /letsencrypt/letsencrypt/csr/0017_csr-certbot.pem
2020-06-25 10:21:55,409:DEBUG:acme.client:Requesting fresh nonce
2020-06-25 10:21:55,409:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2020-06-25 10:21:55,590:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2020-06-25 10:21:55,591:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Thu, 25 Jun 2020 10:21:55 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0102Ba2N5THMyIpTNEYC1N9FIa7bXHda8tLmCwheClQYAgQ
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2020-06-25 10:21:55,592:DEBUG:acme.client:Storing nonce: 0102Ba2N5THMyIpTNEYC1N9FIa7bXHda8tLmCwheClQYAgQ
2020-06-25 10:21:55,593:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "acme.com"\n    },\n    {\n      "type": "dns",\n      "value": "*.acme.com"\n    }\n  ]\n}'
2020-06-25 10:21:55,599:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "REDACTED",
  "signature": "REDACTED",
  "payload": "REDACTED"
}
2020-06-25 10:21:55,897:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 465
2020-06-25 10:21:55,899:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Thu, 25 Jun 2020 10:21:55 GMT
Content-Type: application/json
Content-Length: 465
Connection: keep-alive
Boulder-Requester: 85006890
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-v02.api.letsencrypt.org/acme/order/85006890/3918569970
Replay-Nonce: 0102_WXwm0Ukd2qNThGzCi53fIMEbKP1uxNstPmIr932CJQ
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "pending",
  "expires": "2020-07-02T09:45:34Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "*.acme.com"
    },
    {
      "type": "dns",
      "value": "acme.com"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/5467448243",
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/5467448244"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/85006890/3918569970"
}
2020-06-25 10:21:55,900:DEBUG:acme.client:Storing nonce: 0102_WXwm0Ukd2qNThGzCi53fIMEbKP1uxNstPmIr932CJQ
2020-06-25 10:21:55,901:DEBUG:acme.client:JWS payload:
b''
2020-06-25 10:21:55,907:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/5467448243:
{
  "protected": "REDACTED",
  "signature": "REDACTED",
  "payload": ""
}
2020-06-25 10:21:56,204:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/5467448243 HTTP/1.1" 200 383
2020-06-25 10:21:56,206:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Thu, 25 Jun 2020 10:21:56 GMT
Content-Type: application/json
Content-Length: 383
Connection: keep-alive
Boulder-Requester: 85006890
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0102ujvB_oNg2qfUYnqKqMkCvzKUEM5qLlqnW6oxH0iejF0
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "acme.com"
  },
  "status": "pending",
  "expires": "2020-07-02T09:45:34Z",
  "challenges": [
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/5467448243/eOJt3Q",
      "token": "REDACTED"
    }
  ],
  "wildcard": true
}
2020-06-25 10:21:56,207:DEBUG:acme.client:Storing nonce: 0102ujvB_oNg2qfUYnqKqMkCvzKUEM5qLlqnW6oxH0iejF0
2020-06-25 10:21:56,208:DEBUG:acme.client:JWS payload:
b''
2020-06-25 10:21:56,213:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/5467448244:
{
  "protected": "REDACTED",
  "signature": "REDACTED",
  "payload": ""
}
2020-06-25 10:21:56,409:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/5467448244 HTTP/1.1" 200 789
2020-06-25 10:21:56,409:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Thu, 25 Jun 2020 10:21:56 GMT
Content-Type: application/json
Content-Length: 789
Connection: keep-alive
Boulder-Requester: 85006890
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0102peSuRPbzBk2f8TFtDBvcDFPqwyf-hsfVuH1tSk2hCFs
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "acme.com"
  },
  "status": "pending",
  "expires": "2020-07-02T09:45:34Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/5467448244/FfMO1Q",
      "token": "REDACTED"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/5467448244/gmv0Ug",
      "token": "REDACTED"
    },
    {
      "type": "tls-alpn-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/5467448244/OMCWkw",
      "token": "REDACTED"
    }
  ]
}
2020-06-25 10:21:56,409:DEBUG:acme.client:Storing nonce: 0102peSuRPbzBk2f8TFtDBvcDFPqwyf-hsfVuH1tSk2hCFs
2020-06-25 10:21:56,410:INFO:certbot._internal.auth_handler:Performing the following challenges:
2020-06-25 10:21:56,410:INFO:certbot._internal.auth_handler:dns-01 challenge for acme.com
2020-06-25 10:21:56,410:INFO:certbot._internal.auth_handler:dns-01 challenge for acme.com
2020-06-25 10:21:56,410:WARNING:certbot.plugins.dns_common:Unsafe permissions on credentials configuration file: letsencrypt/active24.ini
2020-06-25 10:21:56,412:DEBUG:certbot_dns_active24.dns_active24:Attempting to add record: _acme-challenge
2020-06-25 10:21:56,414:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.active24.com:443
2020-06-25 10:21:56,560:DEBUG:urllib3.connectionpool:https://api.active24.com:443 "GET /dns/acme.com/records/v1 HTTP/1.1" 200 1717
2020-06-25 10:21:56,569:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.active24.com:443
2020-06-25 10:21:57,843:DEBUG:urllib3.connectionpool:https://api.active24.com:443 "POST /dns/acme.com/txt/v1 HTTP/1.1" 204 0
2020-06-25 10:21:57,848:DEBUG:certbot_dns_active24.dns_active24:Successfully added TXT record
2020-06-25 10:21:57,856:DEBUG:certbot_dns_active24.dns_active24:Attempting to add record: _acme-challenge
2020-06-25 10:21:57,860:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.active24.com:443
2020-06-25 10:21:58,456:DEBUG:urllib3.connectionpool:https://api.active24.com:443 "GET /dns/acme.com/records/v1 HTTP/1.1" 200 1864
2020-06-25 10:21:58,459:DEBUG:certbot_dns_active24.dns_active24:Record exists, but content doesn't match, updating
2020-06-25 10:21:58,461:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.active24.com:443
2020-06-25 10:21:59,686:DEBUG:urllib3.connectionpool:https://api.active24.com:443 "PUT /dns/acme.com/txt/v1 HTTP/1.1" 204 0
2020-06-25 10:21:59,691:DEBUG:certbot_dns_active24.dns_active24:Successfully added TXT record
2020-06-25 10:21:59,695:INFO:certbot.plugins.dns_common:Waiting 360 seconds for DNS changes to propagate
2020-06-25 10:27:59,841:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/certbot/_internal/auth_handler.py", line 70, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/usr/local/lib/python3.8/site-packages/certbot_dns_active24/dns_active24.py", line 60, in perform
    _wait_for_propagation(achalls)
  File "/usr/local/lib/python3.8/site-packages/certbot_dns_active24/dns_active24.py", line 76, in _wait_for_propagation
    queue = [(ns, o[1], o[2]) for o in queue for ns in _get_nameservers(o[0])]
  File "/usr/local/lib/python3.8/site-packages/certbot_dns_active24/dns_active24.py", line 76, in <listcomp>
    queue = [(ns, o[1], o[2]) for o in queue for ns in _get_nameservers(o[0])]
  File "/usr/local/lib/python3.8/site-packages/certbot_dns_active24/dns_active24.py", line 111, in _get_nameservers
    rrset = answer if len(answer) > 0 else answer.response.authority[0]
IndexError: list index out of range

2020-06-25 10:27:59,841:DEBUG:certbot._internal.error_handler:Calling registered functions
2020-06-25 10:27:59,841:INFO:certbot._internal.auth_handler:Cleaning up challenges
2020-06-25 10:27:59,845:DEBUG:certbot_dns_active24.dns_active24:Attempting to delete record: _acme-challenge
2020-06-25 10:27:59,852:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.active24.com:443
2020-06-25 10:28:00,484:DEBUG:urllib3.connectionpool:https://api.active24.com:443 "GET /dns/acme.com/records/v1 HTTP/1.1" 200 1864
2020-06-25 10:28:00,498:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.active24.com:443
2020-06-25 10:28:01,845:DEBUG:urllib3.connectionpool:https://api.active24.com:443 "DELETE /dns/acme.com/F53DAE36FDB22CE6F5131747F6E72B33/v1 HTTP/1.1" 204 0
2020-06-25 10:28:01,851:DEBUG:certbot_dns_active24.dns_active24:Successfully deleted TXT record.
2020-06-25 10:28:01,855:DEBUG:certbot_dns_active24.dns_active24:Attempting to delete record: _acme-challenge
2020-06-25 10:28:01,859:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.active24.com:443
2020-06-25 10:28:02,727:DEBUG:urllib3.connectionpool:https://api.active24.com:443 "GET /dns/acme.com/records/v1 HTTP/1.1" 200 1717
2020-06-25 10:28:02,736:DEBUG:certbot_dns_active24.dns_active24:Record doesn't appear to exist, aborting
2020-06-25 10:28:02,737:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/usr/local/lib/python3.8/site-packages/certbot/_internal/main.py", line 1347, in main
    return config.func(config, plugins)
  File "/usr/local/lib/python3.8/site-packages/certbot/_internal/main.py", line 1233, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/usr/local/lib/python3.8/site-packages/certbot/_internal/main.py", line 121, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/usr/local/lib/python3.8/site-packages/certbot/_internal/client.py", line 409, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/usr/local/lib/python3.8/site-packages/certbot/_internal/client.py", line 343, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/usr/local/lib/python3.8/site-packages/certbot/_internal/client.py", line 390, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/usr/local/lib/python3.8/site-packages/certbot/_internal/auth_handler.py", line 70, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/usr/local/lib/python3.8/site-packages/certbot_dns_active24/dns_active24.py", line 60, in perform
    _wait_for_propagation(achalls)
  File "/usr/local/lib/python3.8/site-packages/certbot_dns_active24/dns_active24.py", line 76, in _wait_for_propagation
    queue = [(ns, o[1], o[2]) for o in queue for ns in _get_nameservers(o[0])]
  File "/usr/local/lib/python3.8/site-packages/certbot_dns_active24/dns_active24.py", line 76, in <listcomp>
    queue = [(ns, o[1], o[2]) for o in queue for ns in _get_nameservers(o[0])]
  File "/usr/local/lib/python3.8/site-packages/certbot_dns_active24/dns_active24.py", line 111, in _get_nameservers
    rrset = answer if len(answer) > 0 else answer.response.authority[0]
IndexError: list index out of range
2020-06-25 10:28:02,741:ERROR:certbot._internal.log:An unexpected error occurred:
2020-06-25 10:28:02,742:ERROR:certbot._internal.log:IndexError: list index out of range

```

**Comment by jahudka** [comment]
Hi, it's still the same issue.. well, I've now released v1.1.15 which resolves nameservers completely differently, so it should hopefully change _something_. As a side note, you should `chmod go-rwx` the `active24.ini` file - it should only be readable by the owner, which should be root. Let me know if the new version helps.

**Comment by rkosegi** [comment]
@jahudka thanks for quick response.

I just tried new version (1.1.15) and behavior is bit different, however it still fails. I specified DNS propagation time as 120 seconds.
certbot kept running for more then 15 minutes, at which point I killed it (CTRL+C).
Here is log (trimmed to interesting part only):

```
2020-06-25 14:42:00,210:DEBUG:certbot_dns_active24.dns_active24:Attempting to add record: _acme-challenge
2020-06-25 14:42:00,214:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.active24.com:443
2020-06-25 14:42:00,389:DEBUG:urllib3.connectionpool:https://api.active24.com:443 "GET /dns/domain.tld/records/v1 HTTP/1.1" 200 1717
2020-06-25 14:42:00,401:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.active24.com:443
2020-06-25 14:42:01,518:DEBUG:urllib3.connectionpool:https://api.active24.com:443 "POST /dns/domain.tld/txt/v1 HTTP/1.1" 204 0
2020-06-25 14:42:01,523:DEBUG:certbot_dns_active24.dns_active24:Successfully added TXT record
2020-06-25 14:42:01,530:DEBUG:certbot_dns_active24.dns_active24:Attempting to add record: _acme-challenge
2020-06-25 14:42:01,535:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.active24.com:443
2020-06-25 14:42:02,030:DEBUG:urllib3.connectionpool:https://api.active24.com:443 "GET /dns/domain.tld/records/v1 HTTP/1.1" 200 1864
2020-06-25 14:42:02,037:DEBUG:certbot_dns_active24.dns_active24:Record exists, but content doesn't match, updating
2020-06-25 14:42:02,041:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.active24.com:443
2020-06-25 14:42:03,259:DEBUG:urllib3.connectionpool:https://api.active24.com:443 "PUT /dns/domain.tld/txt/v1 HTTP/1.1" 204 0
2020-06-25 14:42:03,263:DEBUG:certbot_dns_active24.dns_active24:Successfully added TXT record
2020-06-25 14:42:03,268:INFO:certbot.plugins.dns_common:Waiting 120 seconds for DNS changes to propagate
2020-06-25 14:44:03,506:DEBUG:certbot_dns_active24.dns_active24:Waiting for propagation to authoritative servers
2020-06-25 14:44:34,686:DEBUG:certbot_dns_active24.dns_active24:Remaining records to check: 2
2020-06-25 14:45:05,912:DEBUG:certbot_dns_active24.dns_active24:Remaining records to check: 2
2020-06-25 14:45:37,131:DEBUG:certbot_dns_active24.dns_active24:Remaining records to check: 2
2020-06-25 14:46:08,354:DEBUG:certbot_dns_active24.dns_active24:Remaining records to check: 2
2020-06-25 14:46:40,569:DEBUG:certbot_dns_active24.dns_active24:Remaining records to check: 2
2020-06-25 14:47:12,794:DEBUG:certbot_dns_active24.dns_active24:Remaining records to check: 2
2020-06-25 14:47:44,198:DEBUG:certbot_dns_active24.dns_active24:Remaining records to check: 2
2020-06-25 14:48:15,711:DEBUG:certbot_dns_active24.dns_active24:Remaining records to check: 2
2020-06-25 14:48:46,828:DEBUG:certbot_dns_active24.dns_active24:Remaining records to check: 2
2020-06-25 14:49:18,368:DEBUG:certbot_dns_active24.dns_active24:Remaining records to check: 2
2020-06-25 14:49:49,574:DEBUG:certbot_dns_active24.dns_active24:Remaining records to check: 2
2020-06-25 14:50:20,946:DEBUG:certbot_dns_active24.dns_active24:Remaining records to check: 2
2020-06-25 14:50:52,223:DEBUG:certbot_dns_active24.dns_active24:Remaining records to check: 2
2020-06-25 14:51:23,596:DEBUG:certbot_dns_active24.dns_active24:Remaining records to check: 2
2020-06-25 14:51:54,891:DEBUG:certbot_dns_active24.dns_active24:Remaining records to check: 2
2020-06-25 14:52:26,241:DEBUG:certbot_dns_active24.dns_active24:Remaining records to check: 2
2020-06-25 14:52:57,627:DEBUG:certbot_dns_active24.dns_active24:Remaining records to check: 2
2020-06-25 14:53:28,990:DEBUG:certbot_dns_active24.dns_active24:Remaining records to check: 2
2020-06-25 14:54:00,408:DEBUG:certbot_dns_active24.dns_active24:Remaining records to check: 2
2020-06-25 14:54:31,720:DEBUG:certbot_dns_active24.dns_active24:Remaining records to check: 2
2020-06-25 14:55:02,998:DEBUG:certbot_dns_active24.dns_active24:Remaining records to check: 2
2020-06-25 14:55:34,573:DEBUG:certbot_dns_active24.dns_active24:Remaining records to check: 2
2020-06-25 14:56:06,459:DEBUG:certbot_dns_active24.dns_active24:Remaining records to check: 2
2020-06-25 14:56:37,825:DEBUG:certbot_dns_active24.dns_active24:Remaining records to check: 2
2020-06-25 14:57:09,523:DEBUG:certbot_dns_active24.dns_active24:Remaining records to check: 2
2020-06-25 14:57:41,022:DEBUG:certbot_dns_active24.dns_active24:Remaining records to check: 2
2020-06-25 14:58:12,411:DEBUG:certbot_dns_active24.dns_active24:Remaining records to check: 2
2020-06-25 14:58:43,704:DEBUG:certbot_dns_active24.dns_active24:Remaining records to check: 2
2020-06-25 14:59:16,149:DEBUG:certbot_dns_active24.dns_active24:Remaining records to check: 2
2020-06-25 14:59:47,977:DEBUG:certbot_dns_active24.dns_active24:Remaining records to check: 2
2020-06-25 15:00:07,200:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/certbot/_internal/auth_handler.py", line 70, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/usr/local/lib/python3.8/site-packages/certbot_dns_active24/dns_active24.py", line 60, in perform
    _wait_for_propagation(achalls)
  File "/usr/local/lib/python3.8/site-packages/certbot_dns_active24/dns_active24.py", line 89, in _wait_for_propagation
    sleep(1)
KeyboardInterrupt

2020-06-25 15:00:07,200:DEBUG:certbot._internal.error_handler:Calling registered functions
2020-06-25 15:00:07,200:INFO:certbot._internal.auth_handler:Cleaning up challenges
2020-06-25 15:00:07,202:DEBUG:certbot_dns_active24.dns_active24:Attempting to delete record: _acme-challenge
2020-06-25 15:00:07,204:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.active24.com:443
2020-06-25 15:00:07,789:DEBUG:urllib3.connectionpool:https://api.active24.com:443 "GET /dns/domain.tld/records/v1 HTTP/1.1" 200 1864
2020-06-25 15:00:07,796:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.active24.com:443
2020-06-25 15:00:09,017:DEBUG:urllib3.connectionpool:https://api.active24.com:443 "DELETE /dns/domain.tld/REDACTED/v1 HTTP/1.1" 204 0
2020-06-25 15:00:09,020:DEBUG:certbot_dns_active24.dns_active24:Successfully deleted TXT record.
2020-06-25 15:00:09,022:DEBUG:certbot_dns_active24.dns_active24:Attempting to delete record: _acme-challenge
2020-06-25 15:00:09,023:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.active24.com:443
2020-06-25 15:00:09,480:DEBUG:urllib3.connectionpool:https://api.active24.com:443 "GET /dns/domain.tld/records/v1 HTTP/1.1" 200 1717
2020-06-25 15:00:09,488:DEBUG:certbot_dns_active24.dns_active24:Record doesn't appear to exist, aborting
2020-06-25 15:00:09,489:ERROR:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/usr/local/lib/python3.8/site-packages/certbot/_internal/main.py", line 1347, in main
    return config.func(config, plugins)
  File "/usr/local/lib/python3.8/site-packages/certbot/_internal/main.py", line 1233, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/usr/local/lib/python3.8/site-packages/certbot/_internal/main.py", line 121, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/usr/local/lib/python3.8/site-packages/certbot/_internal/client.py", line 409, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/usr/local/lib/python3.8/site-packages/certbot/_internal/client.py", line 343, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/usr/local/lib/python3.8/site-packages/certbot/_internal/client.py", line 390, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/usr/local/lib/python3.8/site-packages/certbot/_internal/auth_handler.py", line 70, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/usr/local/lib/python3.8/site-packages/certbot_dns_active24/dns_active24.py", line 60, in perform
    _wait_for_propagation(achalls)
  File "/usr/local/lib/python3.8/site-packages/certbot_dns_active24/dns_active24.py", line 89, in _wait_for_propagation
    sleep(1)
KeyboardInterrupt
```

**Comment by jahudka** [comment]
Hi, well, the thing is that the propagation delay you can specify through the options isn't really useful - Active24 has three authoritative servers, and since Let's Encrypt picks one at random when verifying the challenge, my plugin actually waits till all three start showing the correct record - but it can take some time before they do, that's the "Remaining records to check: .." bit in the log - two of the three servers still weren't giving the correct response. So try running it again in `screen` or something similar and let it run for as long as it wants - you can set the DNS propagation time to zero even, because that would be applied only after the plugin already ensured the records have, indeed, propagated, so you don't need it (it's there only because it's specified by the base DNS authenticator class that my plugin extends).

**Comment by rkosegi** [comment]
@jahudka I made another try, given that you made some recent fixes - unfortunately still no luck.

However, I'm able to obtain certificates by simply disabling wait for propagation (https://github.com/rkosegi/certbot-dns-active24/commit/9463511db5215d6a514455176858b3734c078658) and providing argument `--dns-active24-propagation-seconds 600` (which seems to be sufficient for acme server)

Can you make wait for propagation optional (via some CLI argument)?

**Comment by rumman23** [comment]
@jahudka Hi, Im facing exactly same issue. Dns query returns response with answer that is not correctly parsed:
```
;QUESTION
foo.example.com. IN TXT
;ANSWER
foo.example.com. 300 IN TXT "AT******Gk"
```

It looks like that odict object with answer throws `KeyError` when the value is accessed with `strings = result.answer[0].items[0].strings`. 

Different access with `result.answer[0][0].strings` or `result.answer[0].to_text()` works.
Module versions are:

```
pip3 show dnspython
Name: dnspython
Version: 2.0.0

pip3 show certbot-dns-active24
Name: certbot-dns-active24
Version: 1.1.17
```

**Comment by jahudka** [comment]
Hi @rumman23, thanks for reporting this, I'll try to get a fix published asap, but I'm a little strapped for time right now, so it probably won't be before the weekend.. sorry!

**Comment by jahudka** [comment]
Okay guys, I've published yet another attempt at fixing this issue once and for all; this new update also skips explicit propagation checks if the `propagation-seconds` config parameter is > 0 (which is a built-in parameter of the DNS Authenticator base class which makes it wait a fixed interval before returning control to Certbot). Please try it and let me know if it works.

**Comment by rkosegi** [comment]
@jahudka again sorry for late reply. Version `1.2.0` is working as expected. Thanks.
